Early abort if SHA request fails

diff --git a/.github/workflows/update-api-schemas.yml b/.github/workflows/update-api-schemas.yml
--- a/.github/workflows/update-api-schemas.yml
+++ b/.github/workflows/update-api-schemas.yml
@@ -22,6 +22,12 @@ jobs:
           LATEST_COMMIT=$(curl -s -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/cloudflare/api-schemas/commits/main | \
             jq -r '.sha')
+
+          if ! [[ "$LATEST_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then
+            echo "Error: Unexpected value received for commit SHA: '$LATEST_COMMIT'"
+            exit 1
+          fi
+
           echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
 
       - name: Check current commit reference
